name: "BUILD IMAGES"

on:
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer packages
        uses: actions/cache@v1
        env:
          cache-name: cache-composer-packages
        with:
          path: ~/.composer
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run tests
        run: |
          docker-compose --file docker-compose.test.yaml build --force-rm --compress
          docker-compose --file docker-compose.test.yaml up -d
          docker-compose --file docker-compose.test.yaml run --rm composer install
          docker-compose --file docker-compose.test.yaml run --rm sut

  build_images:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build a new container
        run: |
          echo ${{ secrets.PACKAGE_TOKEN }} | docker login docker.pkg.github.com -u ${{ secrets.USER_NAME }} --password-stdin
          docker build --tag docker.pkg.github.com/tommyheavenly7/wp5-host/php-cli:7.4 ./docker/php-cli/
          docker push docker.pkg.github.com/tommyheavenly7/wp5-host/php-cli:7.4
          docker build --tag docker.pkg.github.com/tommyheavenly7/wp5-host/php-fpm:7.4 ./docker/php/
          docker push docker.pkg.github.com/tommyheavenly7/wp5-host/php-fpm:7.4
